/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\BigBattri.glb --transform 
Files: .\public\BigBattri.glb [42.83MB] > BigBattri-transformed.glb [2.9MB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BigBattri-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.025, -0.335]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/BigBattri-transformed.glb')
