/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 .\public\PlayerCharacter.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/PlayerCharacter.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Elf_Swordmaster" position={[0, -0.001, 0]}>
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <group name="ElfSwordmaster_Body">
            <skinnedMesh name="Mesh033" geometry={nodes.Mesh033.geometry} material={materials.ElfSwordmaster_Body} skeleton={nodes.Mesh033.skeleton} />
            <lineSegments name="Mesh033_1" geometry={nodes.Mesh033_1.geometry} material={materials.ElfSwordmaster_Body} />
          </group>
          <skinnedMesh name="ElfSwordmaster_Armor_Arms" geometry={nodes.ElfSwordmaster_Armor_Arms.geometry} material={materials.ElfSwordmaster_Armor_Arms} skeleton={nodes.ElfSwordmaster_Armor_Arms.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Chest" geometry={nodes.ElfSwordmaster_Armor_Chest.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Chest.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Earings" geometry={nodes.ElfSwordmaster_Armor_Earings.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Earings.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Hips" geometry={nodes.ElfSwordmaster_Armor_Hips.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Hips.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Hips_Cloth_Back" geometry={nodes.ElfSwordmaster_Armor_Hips_Cloth_Back.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Hips_Cloth_Back.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Hips_Cloth_Front" geometry={nodes.ElfSwordmaster_Armor_Hips_Cloth_Front.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Hips_Cloth_Front.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_KneeBottomL" geometry={nodes.ElfSwordmaster_Armor_KneeBottomL.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_KneeBottomL.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_KneeBottomR" geometry={nodes.ElfSwordmaster_Armor_KneeBottomR.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_KneeBottomR.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_KneeTopL" geometry={nodes.ElfSwordmaster_Armor_KneeTopL.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_KneeTopL.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_KneeTopR" geometry={nodes.ElfSwordmaster_Armor_KneeTopR.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_KneeTopR.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_LegsL" geometry={nodes.ElfSwordmaster_Armor_LegsL.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_LegsL.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_LegsR" geometry={nodes.ElfSwordmaster_Armor_LegsR.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_LegsR.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Panties" geometry={nodes.ElfSwordmaster_Armor_Panties.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Panties.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Hair" geometry={nodes.ElfSwordmaster_Hair.geometry} material={materials.Elfswordmaster_Hair} skeleton={nodes.ElfSwordmaster_Hair.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_ChestExposed" geometry={nodes.ElfSwordmaster_Armor_ChestExposed.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_ChestExposed.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Hips_Exposed" geometry={nodes.ElfSwordmaster_Armor_Hips_Exposed.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Hips_Exposed.skeleton} />
        </group>
        <mesh name="ElfSwordmaster_Weapon" geometry={nodes.ElfSwordmaster_Weapon.geometry} material={materials.ElfSwordmaster_Weapon} position={[-0.107, 1.2, 0.208]} rotation={[2.408, -0.384, 1.888]} />
      </group>
    </group>
  )
}

useGLTF.preload('/PlayerCharacter.glb')
