/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 .\public\Tifa.glb
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { useControls } from 'leva'

export default function Tifa(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./Tifa.glb')
  const { actions } = useAnimations(animations, group)

  const { animationName } = useControls({
    animationName: { options: Object.keys(actions) }
  })

  useEffect(() => {
    actions[animationName].reset().fadeIn(0.5).play()

    return () => { actions[animationName].fadeOut(0.5) }

  }, [animationName])

  // useEffect(() => {
  //   actions.bend.play();

  //   const timeout = setTimeout(() => {
  //     actions.jump.play()
  //     actions.jump.crossFadeFrom(actions.bend, 1)
  //   }, 8000)
    
  //   return () => clearTimeout(timeout)
  // })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="breastL_spring" position={[0.096, 1.608, 0.146]} />
        <group name="breastR_spring" position={[-0.095, 1.608, 0.146]} />
        <group name="hips_spring" position={[0.001, 1.441, -0.171]} />
        <group name="ButtL_spring" position={[0.089, 1.278, -0.101]} />
        <group name="ButtR_spring" position={[-0.085, 1.337, -0.263]} />
        <group name="rig">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-hand_pole_ik_socketR']} />
          <primitive object={nodes['MCH-hand_ik_socketR']} />
          <primitive object={nodes['MCH-hand_pole_ik_socketL']} />
          <primitive object={nodes['MCH-hand_ik_socketL']} />
          <primitive object={nodes['MCH-foot_pole_ik_socketR']} />
          <primitive object={nodes['MCH-foot_ik_socketR']} />
          <primitive object={nodes['MCH-foot_pole_ik_socketL']} />
          <primitive object={nodes['MCH-foot_ik_socketL']} />
          <group name="Tifa_Arms">
            <skinnedMesh name="Mesh005" geometry={nodes.Mesh005.geometry} material={materials.Tifa_Arms} skeleton={nodes.Mesh005.skeleton} />
            <skinnedMesh name="Mesh005_1" geometry={nodes.Mesh005_1.geometry} material={materials.Tifa_Accs} skeleton={nodes.Mesh005_1.skeleton} />
          </group>
          <skinnedMesh name="Tifa_Belt" geometry={nodes.Tifa_Belt.geometry} material={materials.Tifa_Tops} skeleton={nodes.Tifa_Belt.skeleton} />
          <group name="Tifa_Body_FullNude">
            <skinnedMesh name="Mesh030" geometry={nodes.Mesh030.geometry} material={materials.Tifa_Face} skeleton={nodes.Mesh030.skeleton} />
            <skinnedMesh name="Mesh030_1" geometry={nodes.Mesh030_1.geometry} material={materials.Tifa_Body} skeleton={nodes.Mesh030_1.skeleton} />
          </group>
          <skinnedMesh name="Tifa_Body_Tounge" geometry={nodes.Tifa_Body_Tounge.geometry} material={materials.Tifa_Face} skeleton={nodes.Tifa_Body_Tounge.skeleton} />
          <skinnedMesh name="Tifa_Earrings" geometry={nodes.Tifa_Earrings.geometry} material={materials.Tifa_Accs} skeleton={nodes.Tifa_Earrings.skeleton} />
          <skinnedMesh name="Tifa_Eyelashes" geometry={nodes.Tifa_Eyelashes.geometry} material={materials.Tifa_Eyelashes} skeleton={nodes.Tifa_Eyelashes.skeleton} />
          <group name="Tifa_Hair">
            <skinnedMesh name="Mesh019" geometry={nodes.Mesh019.geometry} material={materials.Tifa_Hair} skeleton={nodes.Mesh019.skeleton} />
            <skinnedMesh name="Mesh019_1" geometry={nodes.Mesh019_1.geometry} material={materials.Tifa_HairPin} skeleton={nodes.Mesh019_1.skeleton} />
          </group>
          <skinnedMesh name="Tifa_Legs" geometry={nodes.Tifa_Legs.geometry} material={materials.Tifa_Legs} skeleton={nodes.Tifa_Legs.skeleton} />
          <skinnedMesh name="Tifa_Top" geometry={nodes.Tifa_Top.geometry} material={materials.Tifa_Tops} skeleton={nodes.Tifa_Top.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./Tifa.glb')

