/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\BigBattri.glb 
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Battri = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/BigBattri-transformed.glb')
  return (
    <group {...props} ref={ref} dispose={null}>
     <group position={[0, -0.025, -0.335]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
})

export default Battri

useGLTF.preload('/BigBattri-transformed.glb')

