/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 .\public\Elf.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Elf(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./Elf.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Bend.play();

    setTimeout(() => {
      actions['Elf_SwordmasterAction.004'].play()
      actions['Elf_SwordmasterAction.004'].crossFadeFrom(actions.Bend, 1)
    }, 8000)
  })

  return (
    <group rotation-x={Math.PI / 8} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="breastL_spring" position={[0.186, 1.025, 0.078]} />
        <group name="breastL001_spring" position={[0.186, 1.024, 0.082]} />
        <group name="breastR_spring" position={[0.014, 1.028, 0.086]} />
        <group name="breastR001_spring" position={[0.014, 1.027, 0.091]} />
        <group name="ButtR_spring" position={[-0.032, 0.777, -0.264]} />
        <group name="ButtL_spring" position={[0.188, 0.773, -0.275]} />
        <group name="Elf_Swordmaster">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <group name="ElfSwordmaster_Body">
            <skinnedMesh name="Mesh033" geometry={nodes.Mesh033.geometry} material={materials.ElfSwordmaster_Body} skeleton={nodes.Mesh033.skeleton} />
            <skinnedMesh name="Mesh033_1" geometry={nodes.Mesh033_1.geometry} material={materials.ElfSwordmaster_Face} skeleton={nodes.Mesh033_1.skeleton} />
          </group>
          <skinnedMesh name="ElfSwordmaster_Armor_Arms" geometry={nodes.ElfSwordmaster_Armor_Arms.geometry} material={materials.ElfSwordmaster_Armor_Arms} skeleton={nodes.ElfSwordmaster_Armor_Arms.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Chest" geometry={nodes.ElfSwordmaster_Armor_Chest.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Chest.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_ChestExposed" geometry={nodes.ElfSwordmaster_Armor_ChestExposed.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_ChestExposed.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Earings" geometry={nodes.ElfSwordmaster_Armor_Earings.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Earings.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Hips" geometry={nodes.ElfSwordmaster_Armor_Hips.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Hips.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Hips_Exposed" geometry={nodes.ElfSwordmaster_Armor_Hips_Exposed.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Hips_Exposed.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_KneeBottomL" geometry={nodes.ElfSwordmaster_Armor_KneeBottomL.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_KneeBottomL.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_KneeBottomR" geometry={nodes.ElfSwordmaster_Armor_KneeBottomR.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_KneeBottomR.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_KneeTopL" geometry={nodes.ElfSwordmaster_Armor_KneeTopL.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_KneeTopL.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_KneeTopR" geometry={nodes.ElfSwordmaster_Armor_KneeTopR.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_KneeTopR.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_LegsL" geometry={nodes.ElfSwordmaster_Armor_LegsL.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_LegsL.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_LegsR" geometry={nodes.ElfSwordmaster_Armor_LegsR.geometry} material={materials.ElfSwordmaster_Armor_Legs} skeleton={nodes.ElfSwordmaster_Armor_LegsR.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Armor_Panties" geometry={nodes.ElfSwordmaster_Armor_Panties.geometry} material={materials.ElfSwordmaster_Armor_Chest} skeleton={nodes.ElfSwordmaster_Armor_Panties.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Eyeslash" geometry={nodes.ElfSwordmaster_Eyeslash.geometry} material={materials.Elfswordmaster_Hair} skeleton={nodes.ElfSwordmaster_Eyeslash.skeleton} />
          <skinnedMesh name="ElfSwordmaster_Hair" geometry={nodes.ElfSwordmaster_Hair.geometry} material={materials.Elfswordmaster_Hair} skeleton={nodes.ElfSwordmaster_Hair.skeleton} />
          <group name="ElfSwordmaster_Mouth_Tounge">
            <skinnedMesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials.ElfSwordmaster_Face} skeleton={nodes.Mesh004.skeleton} morphTargetDictionary={nodes.Mesh004.morphTargetDictionary} morphTargetInfluences={nodes.Mesh004.morphTargetInfluences} />
            <points name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.ElfSwordmaster_Body} morphTargetDictionary={nodes.Mesh004_1.morphTargetDictionary} morphTargetInfluences={nodes.Mesh004_1.morphTargetInfluences} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./Elf.glb')
