/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\Town.glb --transform scale: [0.25, 0.25, 0.25] 
Files: .\public\Town.glb [22.76MB] > Town-transformed.glb [3MB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Town(props) {
  const { nodes, materials } = useGLTF('/Town-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Door_Frame.geometry} material={materials['Wooden surface scan']} position={[-66.905, 1.522, 73.11]} rotation={[0, 1.301, 0]} />
      <mesh geometry={nodes.Tower.geometry} material={materials['Stone Floor 05 Material.002']} position={[-68.468, 5.266, 74.094]} rotation={[0, 1.301, 0]} scale={[1.009, 1.338, 1.009]} />
      <mesh geometry={nodes.Door.geometry} material={materials['Medieval Door Reinforcement']} position={[-66.598, 0.492, 71.632]} rotation={[0, 1.301, 0]} scale={[1.011, 1.002, 1.011]} />
      <instancedMesh args={[nodes.Cube028.geometry, materials['Stone Floor 05 Material.002'], 8]} instanceMatrix={nodes.Cube028.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder005.geometry, materials['Stone Floor 05 Material.002'], 8]} instanceMatrix={nodes.Cylinder005.instanceMatrix} />
      <instancedMesh args={[nodes.Cube008.geometry, materials['Wooden surface scan'], 8]} instanceMatrix={nodes.Cube008.instanceMatrix} />
      <instancedMesh args={[nodes.Cube037.geometry, materials['Medieval Door Reinforcement'], 7]} instanceMatrix={nodes.Cube037.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/Town-transformed.glb')
