/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\Town.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Town(props) {
  const { nodes, materials } = useGLTF('/Town.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ground.geometry} material={nodes.Ground.material} />
      <mesh geometry={nodes.Pillar.geometry} material={nodes.Pillar.material} position={[100, 0, -100]} />
      <mesh geometry={nodes.Pillar001.geometry} material={nodes.Pillar001.material} position={[100, 0, 100]} />
      <mesh geometry={nodes.Pillar002.geometry} material={nodes.Pillar002.material} position={[-100, 0, 100]} />
      <mesh geometry={nodes.Pillar003.geometry} material={nodes.Pillar003.material} position={[-100, 0, -100]} />
    </group>
  )
}

useGLTF.preload('/Town.glb')
