/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\Town.glb --transform scale: [0.25, 0.25, 0.25] 
Files: .\public\Town.glb [31.3MB] > Town-transformed.glb [4.95MB] (84%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Town(props) {
  const { nodes, materials } = useGLTF('/Town-transformed.glb')
  return (
    <RigidBody mass={1000} type="static">
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Tower009.geometry} material={materials['Stone Wall Flag Floor']} position={[16.742, -0.051, 1.414]} rotation={[-Math.PI, 1.531, -Math.PI]} />
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/Town-transformed.glb')
